import type {PipelineResult} from "./types";

export const fallbackPipeline: PipelineResult = {
  structure_dna: {
    schema_version: "1.0",
    video_id: "sample_001",
    total_duration_sec: 32,
    structure_formula: "hook -> pain_point -> solution -> proof -> cta",
    segments: [
      {
        segment_id: "seg_001",
        function: "hook",
        time_range: [0, 3.2],
        duration_sec: 3.2,
        transcript: "很多人用空气炸锅，第一步就做错了",
        text_pattern: "反常识开头",
        emotion_score: 8,
        pacing: "fast",
        required_material_tags: ["talking_head", "high_energy", "clear_face"],
        packaging: {
          subtitle_density: "high",
          subtitle_style: "bold_keyword_highlight",
          title_bar: "top_hook_title",
          transition: "quick_cut",
          emphasis_elements: ["keyword_pop", "zoom_in"],
        },
      },
      {
        segment_id: "seg_002",
        function: "pain_point",
        time_range: [3.2, 8.4],
        duration_sec: 5.2,
        transcript: "温度太高，外面焦了里面还没熟",
        text_pattern: "问题列举",
        emotion_score: 6,
        pacing: "medium",
        required_material_tags: ["pain_point", "product_context"],
        packaging: {
          subtitle_density: "medium",
          subtitle_style: "problem_red_highlight",
          title_bar: "none",
          transition: "hard_cut",
          emphasis_elements: ["red_marker"],
        },
      },
      {
        segment_id: "seg_003",
        function: "solution",
        time_range: [8.4, 18.5],
        duration_sec: 10.1,
        transcript: "先预热三分钟，再把食材平铺进去",
        text_pattern: "步骤说明",
        emotion_score: 7,
        pacing: "medium",
        required_material_tags: ["product_demo", "hands", "process"],
        packaging: {
          subtitle_density: "medium",
          subtitle_style: "numbered_steps",
          title_bar: "step_card",
          transition: "match_cut",
          emphasis_elements: ["step_badge", "arrow_label"],
        },
      },
    ],
    global_features: {
      pacing_pattern: "fast_start_slow_middle_fast_end",
      bgm_style: "upbeat_electronic",
      overall_emotion_curve: [8, 6, 7, 7, 9],
    },
  },
  material_library: {
    schema_version: "1.0",
    project_id: "case_001",
    target: {
      title: "新品空气炸锅带货短视频",
      category: "product_talk",
      selling_points: ["少油", "外酥里嫩", "一键预热", "易清洗"],
    },
    materials: [
      {
        material_id: "mat_001",
        type: "video_clip",
        file_name: "talking_head_intro.mp4",
        shot_type: "talking_head",
        semantic_role: "hook",
        tags: ["talking_head", "clear_face", "clear_voice"],
        emotion_score: 6,
        quality_score: 0.88,
        crop_risk: "low",
        transcript: "很多人买空气炸锅只看容量，其实第一步就容易错",
      },
      {
        material_id: "mat_002",
        type: "video_clip",
        file_name: "product_process.mp4",
        shot_type: "product_demo",
        semantic_role: "solution",
        tags: ["product_demo", "hands", "process", "food_closeup"],
        emotion_score: 7,
        quality_score: 0.91,
        crop_risk: "low",
        transcript: "先预热，再把鸡翅平铺进去",
      },
    ],
  },
  edit_plan: {
    schema_version: "1.0",
    project_id: "case_001",
    source_structure_id: "sample_001",
    target_title: "新品空气炸锅带货短视频",
    variant: "balanced",
    overall_score: {
      structure_consistency: 0.86,
      material_fit: 0.78,
      pacing_fit: 0.82,
    },
    timeline: [
      {
        segment_id: "seg_001",
        target_segment_id: "target_001",
        function: "hook",
        target_time_range: [0, 3],
        selected_material_id: "mat_001",
        slot_status: "weak_match",
        gap_reason: "素材情绪强度低于样例 hook",
        completion_strategy: "packaging",
        supplement_instruction: "增加顶部标题条和关键词放大动画",
        script: "很多人买空气炸锅，第一步就错了",
        packaging: {subtitle: "bold_keyword_highlight", title_bar_text: "第一步就错了"},
        explanation: "用现有口播承载主体，并通过包装补足冲击力。",
      },
      {
        segment_id: "seg_004",
        target_segment_id: "target_004",
        function: "proof",
        target_time_range: [18, 25.5],
        selected_material_id: "mat_004",
        slot_status: "supplemented",
        gap_reason: "缺少真实前后对比镜头",
        completion_strategy: "copy",
        supplement_instruction: "用卖点卡片和局部放大画面代替真实对比镜头",
        script: "预热后口感更稳定，少油也能做出外酥里嫩",
        packaging: {subtitle: "result_highlight", title_bar_text: "效果证明"},
        explanation: "用文案证明和商品特写组合补足证明段。",
      },
    ],
    missing_slots: [
      {
        segment_id: "seg_004",
        function: "proof",
        missing_type: "comparison_shot",
        impact: "证明力不足，转化说服力下降",
        suggested_fix: "用卖点卡片和商品局部放大替代真实前后对比镜头",
      },
    ],
    exports: {},
  },
  comparison_report: {},
};
